// Generated by https://quicktype.io

export interface IAccountResponse {
    ok:   boolean;
    body: Body;
}

export interface Body {
    email:    string;
    password: string;
    name:     string;
    lastname: string;
    dni:      string;
    id:       number;
}


// Generated by https://quicktype.io

export interface IAccountRequest {
    email:    string;
    password: string;
    name:     string;
    lastname: string;
    dni:      string;
}
