// Generated by https://quicktype.io

export interface IAccountResponse {
    id:      number;
    name:    null;
    dni:     null;
    phone:   null;
    age:     null;
    account: Account;
}

export interface Account {
    id:               number;
    email:            string;
    password:         string;
    rol:              Rol;
    subscriptionPlan: SubscriptionPlan;
}

export interface Rol {
    id:   number;
    name: string;
}

export interface SubscriptionPlan {
    id:    number;
    name:  string;
    price: number;
}
