// Generated by https://quicktype.io

export interface IPersonProfileResponse {
    name:  string;
    dni:   string;
    phone: string;
    age:   string;
    email:   string;
    password:   string;
}
